---
# tasks file for common
- name: Update MOTD
  template:
    src: motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: "0600"
    setype: etc_t

- name: Set SELinux to Permissive
  selinux:
    state: permissive
    policy: targeted

- name: Enable EPEL
  yum:
    name: epel-release
    state: present
